dist: trusty
sudo: required
language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  app:
    master: try-travis
    dev: try-travis
  api_key:
    secure: a1OxUlcIEclpQe76ZBRCAGqNf6Cjw1Ei2G24KlYL5fFsXvGtCjalNX/ipuTcz4ajySTurKPFSP4EsvHeXVxI9iNY7cBXr/E0pLxKRyN+xA1jPt4anJ6ppvXtykEFSFhzeFpAOa2l41aeSgKXnr2tdIVad+qgOGJ81eYj65H2miim4YFKXAqdWXMcD8+mgNmOcr61Gc78e9mL9ZWtCBlDqbbLi9E/+2TYrEtEQOjLzE//Xl/lQa+yUM0orxNntZGQxiP3dZPsrSwtreDaZnDDbN8OuRbHjaQ6LqO8CNLcjUzYHs7vJtGyWFWvog+C66YoqeMJOdmNkIOhN6FgiYPKzuG6Gw71XYr52p9Kg9LMxKwsaoKBBVo06fbERTPvPmif00sbblHS6evmJ37FvzwZZhLjN6VobcMTd8fAGVlOrOHyDkFtU4xyXZqUa32yvAvK48l7bjQfrq24N2BdiJ68HTOORpksEcl8D55P5yM8Z+o6bACeYiuQ1YXPK7wkXjIbxHjDVpmRNnW3m2oJeJ02zuT9eMt2rmO1Gh6XxWm8Xc9d+h/JGSM88QcUWH3aAirCu5r6U44FRneo2P5GnpIHHFrYLKmKpiaKnvAs56U3UwaM8ObmBdrr3QV/MaL6Wyw7Aao2kwhbpGP4NZHXYozMYjplNf5y7s7CIBggAW/QS3k=
script:
- npm test
