dist: trusty
sudo: required
language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  app:
    master: try-travis
    dev: try-travis
  api_key:
    master:
      secure: ZoTUr9zqBUKciy/XPikg3ERRd6CfYNLqQmhF3AxZZIRiBmqXw9J24Uvs16r70OxzftSo1UooghKZxzOnO7CEQcQrfPBTu9Z9IVZ9RB8hx61VsxBPsC8z+r0cM/e9Gpqz44GUzjD1QpFNR6U2FsnwLmqbFdWgp/cqL/ZUwODSiEHH4SFQ3uTyWRTsZJ9gULZ8eDodS/S8WA9Y5BcYMxElbx6d4xmzmk+8B0Mjp90wTvDn1K7fPN5BDZyFzaJ/cOs6a7CEQ5HaK9SFB9IFaUyBOIza2jha9uP8f8IOvoDYsqhLjjg4d98oMmQihuAsbM4x6Du+XhgoYxwMf4YDZbOgNjsAPmiF77mTL4Fss2jl+WS94TdSkN5TJhUtwqZGpoNA9xpNIR/tkfcCy0XbrTUScv4/JSIoG5O3HLboTp15h1gZuHpvi4q6NZcZyK9/R9D6Z8HDUm4EXxd5IMWJv60430cyfZobEC3KN6xY+y6oq85pytS0IOslgg1sqc2P0LuGfkjseAQ8CF1BkqYzyqJxJMn8FTEwqkJaLjnl+qcimDVCZu3mzE9kpbVM++ijaqOLBstxKDlJuqNerGyib8aXzJbZQqEDUsJWRfTjQz7u1WjBRMnxRtdsXvYYMy5CA7uzYfdfvIfXUgsK929rqrOmXKe7sg6bf0PXkqjxTVsSD9s=
    dev:
      secure: ZoTUr9zqBUKciy/XPikg3ERRd6CfYNLqQmhF3AxZZIRiBmqXw9J24Uvs16r70OxzftSo1UooghKZxzOnO7CEQcQrfPBTu9Z9IVZ9RB8hx61VsxBPsC8z+r0cM/e9Gpqz44GUzjD1QpFNR6U2FsnwLmqbFdWgp/cqL/ZUwODSiEHH4SFQ3uTyWRTsZJ9gULZ8eDodS/S8WA9Y5BcYMxElbx6d4xmzmk+8B0Mjp90wTvDn1K7fPN5BDZyFzaJ/cOs6a7CEQ5HaK9SFB9IFaUyBOIza2jha9uP8f8IOvoDYsqhLjjg4d98oMmQihuAsbM4x6Du+XhgoYxwMf4YDZbOgNjsAPmiF77mTL4Fss2jl+WS94TdSkN5TJhUtwqZGpoNA9xpNIR/tkfcCy0XbrTUScv4/JSIoG5O3HLboTp15h1gZuHpvi4q6NZcZyK9/R9D6Z8HDUm4EXxd5IMWJv60430cyfZobEC3KN6xY+y6oq85pytS0IOslgg1sqc2P0LuGfkjseAQ8CF1BkqYzyqJxJMn8FTEwqkJaLjnl+qcimDVCZu3mzE9kpbVM++ijaqOLBstxKDlJuqNerGyib8aXzJbZQqEDUsJWRfTjQz7u1WjBRMnxRtdsXvYYMy5CA7uzYfdfvIfXUgsK929rqrOmXKe7sg6bf0PXkqjxTVsSD9s=
script:
- npm test

